### ISSUE TITLE
COMPILE_ASSERTIONS symbol should be set when NuGet Package is installed

### ISSUE THREAD

**Issue by feO2x** [feO2x/Light.GuardClauses#11]
When the Light.GuardClauses NuGet package is installed, a Powershell Script should be run that sets the COMPILE_ASSERTIONS symbol on the target project (if necessary).

**Comment by bchavez** [comment]
Or make it the default. I would prefer default.

**Comment by feO2x** [comment]
@bchavez Yeah, I almost always forget to set this symbol when I'm installing the package, too. I will address this in the upcoming days.

**Comment by feO2x** [comment]
Implemented in 1c97e1fe7b6b3ec8f63c0775b8213f05e371a600
