### ISSUE TITLE
IsValidEnumValue and MustBeValidEnumValue should be able to handle enumerations marked with the FlagsAttribute

### ISSUE THREAD

**Issue by feO2x** [feO2x/Light.GuardClauses#42]

**Comment by feO2x** [comment]
Implemented in 86f4a9495a617a1d17e2224a912fcb8c443de86e

**Comment by aalmada** [comment]
I was exactly looking for this feature. Any plan to release it on NuGet soon?
Thanks for developing this library. It is great!

**Comment by feO2x** [comment]
Hey @aalmada,
thanks for your kind words. I'm currently optimizing the performance of Light.GuardClauses, which introduces breaking changes. Version 4.0 might be out in about 3 - 4 weeks. Is it possible [that you copy to the code of MustBeValidEnum](https://github.com/feO2x/Light.GuardClauses/blob/1f7adaf829bce816e5992e97acaee72fa41ffb63/Code/Light.GuardClauses/CommonAssertions.cs#L278) to your project and remove it once 4.0 is released?

**Comment by aalmada** [comment]
That's great. Thanks once more.

**Comment by feO2x** [comment]
Hey @aalmada, I just want to let you know that I will postpone the release of version 4.0. I'm currently adding support for .NET 4.0, .NET 3.5 and .NET 3.5 Compact Framework. This results in breaking changes that I only want to take once. I think that I will release Light.GuardClauses 4.0 in about 3 months.

However, I re-implemented MustBeValidEnumValue and its way faster now. You can check it out [here](https://github.com/feO2x/Light.GuardClauses/blob/7052fceca40a582924d13cb3e47340e53dd05fe8/Code/Light.GuardClauses/CommonAssertions.cs#L300).

**Comment by aalmada** [comment]
@feO2x No stress. Thanks for the heads up.
Does anyone still use the Compact Framework?

**Comment by feO2x** [comment]
Indeed I do - at work, we have to support a WinCE Barcode Scanner which only supports .NET 3.5 CF. Windows Forms FTW!
