### ISSUE TITLE
Guard for valid email address

### ISSUE THREAD

**Issue by johanvergeer** [feO2x/Light.GuardClauses#57]
I just started using your library, and so far it is looking great. And at this point I'm missing something that can be used in a couple of my projects. 

Has anyone thought of adding a clause like `string.MustBeValidEmail(); ` . This seems to be something that can be very generic and useful for this library. If you would like this to be added I'm willing to make a contribution.

**Comment by feO2x** [comment]
Hey @johanvergeer,
thanks for your kind words. Sure, let's add this assertion to Light.GuardClauses. Some thinks we should consider:

- I think a regex-based implementation will be the quickest one to implement
- Regular expressions for emails don't seem to be that easy: https://stackoverflow.com/questions/16167983/best-regular-expression-for-email-validation-in-c-sharp#16168103
- Should we include an overload where the user might specify his or her own email regular expression?

You're welcome to implement this assertion and send me a pull request.

**Comment by feO2x** [comment]
BTW: as a workaround, there is already a `string.MustMatch` assertion that you can use while this feature isn't released.

**Comment by johanvergeer** [comment]
Thanks for your fast response. I do have an issue though. 

It seems the project supports a lot of frameworks and I have resolved most of them by now.  The only one left is `.NETFramework,Version=v3.5,Profile=CompactFramework`. The plain ` `.NETFramework,Version=v3.5` is already resolved.

Do you know how I can resolve that last one?

**Comment by feO2x** [comment]
@johanvergeer I suggest you create a `TargetFrameworks.props` file as described in [the building and contributing page in the wiki](https://github.com/feO2x/Light.GuardClauses/wiki/How-to-Contribute-and-Build#changing-the-targetframeworks-for-your-local-development-machine). Thus you do not have to resolve the dependencies that are not installed on your dev machine.

Please take a look at the rest of the wiki, too. If you have any further questions, please feel free to contact me.

**Comment by feO2x** [comment]
Implemented in 38d506d63b9f8c8807833e9af6b31d8264bd4d2e

**Comment by feO2x** [comment]
Hey @johanvergeer,
before I'll publish your new to NuGet, I wanted to take a closer look to the email regular expression that you wrote:

```csharp
new Regex(
    @"^[\w!#$%&'*+\-/=?\^_`{|}~]+(\.[\w!#$%&'*+\-/=?\^_`{|}~]+)*@((((\w+\-?)+\.)+[a-zA-Z]{2,4})|(([0-9]{1,3}\.){3}[0-9]{1,3}))$",
    RegexOptions.CultureInvariant | RegexOptions.ECMAScript)
```

I have several questions:

1. Did you write the expression yourself or did you (partially) copy it from another source? You linked (https://emailregex.com/)[https://emailregex.com/] but the regular expressions on this site for .NET or C# are not identical to the one you wrote.
2. Can you tell if this regular expression works in all cases supported by the official [RFC 2822 specification](https://tools.ietf.org/html/rfc2822), especially section [3.4.1](https://tools.ietf.org/html/rfc2822#section-3.4.1) where email addresses (addr-ref) are defined?
3. Is your regular expression the simplest one we can use? As shown in [the benchmark picture of your pull request](https://user-images.githubusercontent.com/7884158/52162866-1d6e3a80-26da-11e9-8eb5-755fb35c9d28.png), the performance is not that great. My overall goal is to provide fast assertions that only take a few nanoseconds and with `IsEmailAddress` we already are in the range of microseconds. I know email validation is not eazy, but if we could at least arrive in the range of several hundred nanoseconds, that would be great.

**Comment by johanvergeer** [comment]
Hi @feO2x, 

To answer your questions: 

I did use an existing regex pattern to start with, but not from https://emailregex.com/, since that one gave a lot of false positives.
The one I used to start of was from https://www.rhyous.com/2010/06/15/csharp-email-regular-expression/. This one also didn't pass all tests so I made some changes. 

The only ones that won't pass at this moment are:

- local-part surrounded with quotes. e.g. `"hello"@test.com`
- domain address surrounded by square brackets. This is only used for IP addresses. e.g. `hello@[123.123.123.123]`

For the test cases I used [this](https://blogs.msdn.microsoft.com/testing123/2009/02/06/email-address-test-cases/) list from MSDN.

It might be that I missed some that I'm not aware of. 

Regarding performance. This would require some more research. I do know some regex, but I'm not a master in it.

I also have one more question for you. I tried to use `TargetFrameworks.props` as you described in the Wiki, but VS is still showing errers because of the missing dependencies. Is there something else I might be missing? 

Also a suggestion. Would you like to add a `.gitignore` to the project?

**Comment by feO2x** [comment]
Hey @johanvergeer,

1. I will remove the link to https://emailregex.com/, and I will mention that https://www.rhyous.com/2010/06/15/csharp-email-regular-expression/ was used as a basis.
2. I will check if compiling the regex will result in a faster execution time.
3. There already is a .gitignore file:
![gitignore in Repo](https://user-images.githubusercontent.com/7884158/52175344-8b7e3480-27a2-11e9-85f0-ac8a52802707.png)
4. I'm not sure why you cannot load Light.GuardClauses.csproj with a custom TargetFrameworks.props file. Could you show me the specific error messages (and create a new issue for that, together with information about your specific VS version and the installed .NET / .NET Core frameworks)?

**Comment by feO2x** [comment]
Sorry that it took so long, but version 6.2 is now out. You can fetch your contribution on [NuGet](https://www.nuget.org/packages/Light.GuardClauses/6.2.0) or in the [source file](https://github.com/feO2x/Light.GuardClauses/blob/master/Light.GuardClauses.SingleFile.cs).

Thanks again for your contribution!

**Comment by johanvergeer** [comment]
Hi @feO2x, 

Just out of curiosity. Were you able to improve the performance of the regex?

**Comment by feO2x** [comment]
Unfortunately not. I think the key here is to replace the regular expression with plain code, but this would take some time.
