### ISSUE TITLE
Add Check.InvalidArgument

### ISSUE THREAD

**Issue by ironcev** [feO2x/Light.GuardClauses#64]
# Motivation

The `MustXYZ()` guards cover a lot of common guard cases. Still, in the case of arguments, we can always have a need to check some arbitrary condition specific to our application. At the moment, we can use the `InvalidState()` and `InvalidOperation()` methods on the `Check` class to check arbitrary conditions. Those methods throw `InvalidStateException` and `InvalidOperationException`, respectively.

Sometimes, neither the state nor the operation is invalid, but rather the provided argument itself. Therefore, we want to check if the argument is invalid and throw `ArgumentException`.

Moreover, in one case that we have in our application right now, we actually want to throw an application specific exception that communicates that an argument is invalid.

# Proposal

Extend `Check` class with the following `InvalidArgument()` methods:

    public static void InvalidArgument(bool condition, string parameterName = null, string message = null)
    public static void InvalidArgument(bool condition, Func<Exception> exceptionFactory)

The first override throws `ArgumentException`. It could also throw a custom `InvalidArgumentException`.

# Potential Consequences and Alternatives

If we add the `InvalidArgument()` overload that accepts `Func<Exception> exceptionFactory` we should, for the sake of consistency, add the same overload to the existing `InvalidOperation()` and `InvalidState()` methods. Do we want that?

An alternative could be to have just a single `Invalid()` method of the form:

    public static void Invalid(bool condition, Func<Exception> exceptionFactory)

This method can be used in all general cases where no other guard method applies.
Still, I am personally more for having explicit `InvalidOperation/State/Argument()` methods that clearly communicate the guard's semantics.

@feO2x Let me know what you think. If you find the proposal meaningful, I would be happy to contribute with a pull request :-)

BDW, at the moment in our application we fallbacked to a plain if guard:

    if (<condition on argument>) throw new OurCustomException("<message>");

Since we have Light.GuardClauses everywhere, we would like to have it here as well.

**Comment by feO2x** [comment]
I like this proposal. Particularly, I would opt for the following:

- Add the two `InvalidArgument()` overloads, the first throwing an `ArgumentException`, the second throwing a custom exception via `exceptionFactory`.
- The default message for the first overload should be "The value is invalid".
- I wouldn't touch `InvalidOperation()` or `InvalidState()`. They clearly communicate that a special exception is thrown, thus I wouldn't add an overload with an exception factory to them (but we can negotiate that - personally, I use a mixed style of Light.GuardClauses extension method and imperative statements for throwing exceptions in my code, especially when writing parser code).
- I wouldn't create a custom `InvalidArgumentException` - the existing `System.ArgumentException` is fine.

I hope this answers all open points. I would really appreciate your PR! If you have any further questions, please feel free to ask.

**Comment by ironcev** [comment]
No further questions, PR hopefully coming soon :-) Thanks for your quick answer!

**Comment by ironcev** [comment]
After going through all of the remaining plain if guards in our application I've noticed that some of them use the parameter value to form the message text. If we want to support that case and avoid closures we should add the third overload as well:

    public static void InvalidArgument<T>(bool condition, T parameter, Func<T, Exception> exceptionFactory)

What is your opinion on that? Should we add it, or rather treat this case as a corner case and fallback to imperative checks? I would personally love to have the overload.

**Comment by feO2x** [comment]
You're right. Add this overload, too.

**Comment by feO2x** [comment]
Thanks for your PR!

Implemented in 61f454229ac681cd1e09ec098d40c13c92e13564
