### ISSUE TITLE
Use with FxCop?

### ISSUE THREAD

**Issue by rndthoughts** [feO2x/Light.GuardClauses#67]
In my dotnet core web api project I use FxCop and want to use Light.GuardClauses also.  However, FxCop complains about missing ArgumentNull checks when I have added them using the Light.GuardClauses commands.  Is this expected behaviour or am I doing something wrong?

**Comment by rndthoughts** [comment]
Yes, I like Resharper too but I cancelled my subscription because it was too expensive considering what Roslyn can do nowadays.

**Comment by feO2x** [comment]
I will look into this in the upcoming days. The Roslyn analyzer that needs to be replaced is [CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062), the source code of this analyzer is a class named [ValidateArgumentsOfPublicMethods in Microsoft.CodeQuality.Analyzers](https://github.com/dotnet/roslyn-analyzers/blob/a9b86aadc80a604fb14351a84771525af62797d7/src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/ValidateArgumentsOfPublicMethods.cs).

I will first have to analyze it thoroughly and then provide an alternative implementation that also checks for `MustNotBeNull` and other methods that guarantee null-safety.

I will not support Visual Basic - the analyzer to be created will only work with C# projects.

**Comment by feO2x** [comment]
Hey @rndthoughts,
I've just release version 8.0.0 of Light.GuardClauses. It support C# 8 Nullable Reference Types and thus should work with the FxCop Analyzer (if you enable the NRT feature in your projects). Does this solve the issue for you?
I looked at a custom Analyzer, but these are pretty complex and I would need a tremendous amount of time to adapt them for the assertions of Light.GuardClauses.

**Comment by feO2x** [comment]
I will close this issue for now due to inactivity. @rndthoughts please reopen it if we need to investigate this further.
