### ISSUE TITLE
Add MustBeJson and IsJson to Check.StringAssertions.cs

### ISSUE THREAD

**Issue by eliaslopezgt** [feO2x/Light.GuardClauses#68]
When dealing with configuration files, it will be useful to check that the string is a valid Json string before adding it to for example IConfiguration.
A possible implementaiton will be using System.Text.Json's
```public static void MustBeJson(this string input) => JsonSerializer.Deserialize<object>(input);```

**Comment by feO2x** [comment]
Hey Elias,

Thanks for your proposal. Unfortunately, I don't think that this is a good idea. Here are my reasons for this:

- While Light.GuardClauses has dependencies on System.Memory and System.Runtime.CompilerServices.Unsafe, I do not want a reference on a full-blown serialization library. 
- The assertions of Light.GuardClauses should be focused and fast. Nearly all of them take only about 1ns to execute, while parsing JSON usually takes several microseconds up to several milliseconds, depending on the complexity of the document to be deserialized. This wouldn't fit well with the rest of the assertions.
- The `ConfigurationBuilder.Build` method already throws an exception when the JSON is invalid. What is the benefit of wrapping this in another assertion method?

![image](https://user-images.githubusercontent.com/7884158/69345685-d144b480-0c71-11ea-8b58-544d5f2b03cb.png)

**Comment by eliaslopezgt** [comment]
Thanks for that amazing feedback, you are right. Just thought it will be a good idea to have an assertion for that, knowing that it won't be as fast as the other ones because of the parsing but more in terms of adding that validation as a `nice to have`.

**Comment by feO2x** [comment]
No problem, thanks for the proposal. The thing about parsing (and all other code on the process boundary) is "just do it and check for exceptions". Parsing is so expensive that you shouldn't do a run where you check that something is valid and after that parse it again to obtain the actual deserialized object instances.
