### ISSUE TITLE
The image of the video introduction to Light.GuardClauses is not displayed in the README.md

### ISSUE THREAD

**Issue by ironcev** [feO2x/Light.GuardClauses#71]
The image cannot be found and the link looks like this:

![image](https://user-images.githubusercontent.com/4142833/87589358-66a32600-c6e5-11ea-91e9-fd2952599472.png)

It looks like that the image file "https://raw.githubusercontent.com/feO2x/Light.GuardClauses/master/Images/version2-video-logo.png" can't be found:

![image](https://user-images.githubusercontent.com/4142833/87589590-bc77ce00-c6e5-11ea-89db-db91e987548b.png)

Strange, maybe some temporary caching issue with Github, but at the moment looks pretty persistent ;-)

**Comment by feO2x** [comment]
Thanks for the info and sorry for the late reply. I think the link did not work since GitHub changed its design a few weeks back. Banner is visible again since cf60e04c9f9eda00c2da2a2c40c0faf6a5daba30.
