### ISSUE TITLE
Conditional assert

### ISSUE THREAD

**Issue by bigdnf** [feO2x/Light.GuardClauses#73]
I have a question about usage of library. Is it possible to do some condition before assert. for example I have code like this

```
if (!string.IsNullOrEmpty(currency))
{
     currency.MustMatch(_currencyRegex, (s, b) => throw new NumberOfCharsException(nameof(currency), 3));
 }
```

so I would assert only when there is some value and skip when there is no value. Is there a way to do this with some one liner and library support?

**Comment by feO2x** [comment]
Hey @bigdnf,
No, Light.GuardClauses does not support this scenario out of the box. I would suggest that you write your own assertion of you need to provide custom cases like this one.

**Comment by bigdnf** [comment]
I like fast response :)
