### ISSUE TITLE
Extend validation methods for HTML and URL check

### ISSUE THREAD

**Issue by Sacharkin** [feO2x/Light.GuardClauses#75]
Actually I start to use this framework to validate/guard my properties.
But I do not finde a implementation to check HTML content or URLs, this would be nice.
Prefer to use something like:
`value.MustBeHtml()`
`value.MustBeUrl()`

**Comment by feO2x** [comment]
Hey Sacharkin,

unfortunately, I have to disagree with you on the HTML assertion for the following reasons:

- While Light.GuardClauses has dependencies on System.Memory and System.Runtime.CompilerServices.Unsafe, I do not want a reference on a full-blown HTML parsing library (like [AngleSharp](https://anglesharp.github.io/)).
- The assertions of Light.GuardClauses should be focused and fast. Nearly all of them take only about 1ns to execute, while parsing HTML usually takes several microseconds up to several milliseconds, depending on the complexity of the document to be parsed. This wouldn't fit well with the rest of the assertions.

In general, if you have to parse something, then it's not a good fit for Light.GuardClauses. Just parse it and check if the corresponding parser throws an exception or reports any other kinds of errors.

Regarding the URL: there already are [assertions that validate URIs](https://github.com/feO2x/Light.GuardClauses/wiki/Overview-of-All-Assertions#assertions-for-uris). I would suggest you create an URI instance and then use one of the assertions.

Does this fit your needs?

**Comment by feO2x** [comment]
BTW, there already was a similar issue regarding JSON: https://github.com/feO2x/Light.GuardClauses/issues/68

Maybe you want to read it, too.

**Comment by Sacharkin** [comment]
I understand the reasons to not implements this issue. Can be closed. Thanks 👍🏻

**Comment by feO2x** [comment]
No worries! Thanks for your suggestions.
