### ISSUE TITLE
ContractAnnotationAttribute included even when RemoveContractAnnotations = true

### ISSUE THREAD

**Issue by cdonnellytx** [feO2x/Light.GuardClauses#76]
Currently (confirmed 8.1.0, 9.0.0), the `ContractAnnotationAttribute` class is included in the `Light.GuardClauses` namespace even when the source code transformation tool is configured as follows:
```powershell
dotnet run -- --TargetFile out.cs --RemoveContractAnnotations true --IncludeJetBrainsAnnotations false --IncludeJetBrainsAnnotationsUsing false --IncludeCodeAnalysisNullableAttributes false
```

Additionally, the `NotNullAttribute` is also included in the `Light.GuardClauses` namespace.

This causes import issues if using a separate JetBrains.Annotations include (e.g., the one generated by ReSharper):

```csharp
using JetBrains.Annotations;
using Light.GuardClauses;

public class MyClass
{
    public void DoSomething([NotNull] string value, [CanBeNull] object otherValue)
    {
        value.MustNotBeNullOrEmpty(nameof(value));
    }
}
```

MSBuild output:
```
MyClass.cs(25, 57): [CS0104] 'NotNull' is an ambiguous reference between 'JetBrains.Annotations.NotNullAttribute' and 'Light.GuardClauses.NotNullAttribute'
```

Would it be possible to remove those classes completely? `ContractAnnotationAttribute` is not used in this case, and `NotNullAttribute` isn't either (only by `ContractAnnotationAttribute` itself).

Thank you!

**Comment by feO2x** [comment]
Thank you for your issue. Unfortunately, I'm currently in vacation and cannot immediately fix the issue myself.

When I introduced the attributes you just talked about, I did not create any options for the source code transformation tool.

I think we have two options:

1. You export and remove the code you don't want manually. I'll be back at August 25th and can add the options then.
2. You try to extend the source code transformation tool yourself and send me a pull request. I'm sure I can review it somehow.

What do you think is best?

**Comment by cdonnellytx** [comment]
> I think we have two options:
> 1. You export and remove the code you don't want manually. I'll be back at August 25th and can add the options then.
> 2. You try to extend the source code transformation tool yourself and send me a pull request. I'm sure I can review it somehow.
>
> What do you think is best?

I'll go with option 1 for now -- it's low priority, just something I wanted to report.

Enjoy your vacation!

**Comment by feO2x** [comment]
@cdonnellytx
Sorry for taking this long - i fixed this issue with version 10 of Light.GuardClauses.
