### ISSUE TITLE
Add NoEnumerationAttribute to MustNotBeNull checks

### ISSUE THREAD

**Issue by cdonnellytx** [feO2x/Light.GuardClauses#82]
JetBrains annotations now includes a [NoEnumerationAttribute](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#NoEnumerationAttribute):

> Indicates that IEnumerable passed as a parameter is not enumerated. Use this annotation to suppress the 'Possible multiple enumeration of IEnumerable' inspection.

At a minimum I would like to add this to the `MustNotBeNull` and `MustNotBeNullReference` checks, as those check strictly against nulls.

I evaluated other methods as follows:

| Method name              | Safe? | Reason                                 |
|:-------------------------|:-----:|:---------------------------------------|
| `MustNotBeNull`          | ✅    | Does identity check against null       |
| `MustNotBeNullReference` | ✅    | Does identity check against null       |
| `IsSameAs`               | ✅    | Does identity check against two values |
| `MustNotBeSameAs`        | ✅    | Does identity check against two values |
| `MustNotBeDefault`       | ❌    | Calls [Equals] which can be overridden and in theory enumerate. |
| `MustHaveValue`          | ✅    | [HasValue](https://learn.microsoft.com/en-us/dotnet/api/system.nullable-1.hasvalue), [Value](https://learn.microsoft.com/en-us/dotnet/api/system.nullable-1.value) cannot be overridden and do not enumerate |
| `MustBe`                 | ❌    | Calls [Equals] which can be overridden and in theory enumerate. |
| `MustNotBe`              | ❌    | Calls [Equals] which can be overridden and in theory enumerate. |

Everything else either operates on a strictly non-enumerable type (e.g, `MustBeEmpty(Guid)`), on a "well-known" enumerable type that is not streaming (e.g. `string`), or an enumerable that may be streaming.

I have a [branch](https://github.com/cdonnellytx/Light.GuardClauses/tree/feature/noEnumeration) I intend to submit as a PR if you are comfortable with these changes.

Thanks for making a great library!

\# Chris

[Equals]: https://learn.microsoft.com/en-us/dotnet/api/system.object.equals

**Comment by feO2x** [comment]
Hey Chris,

your sugesstions sound reasonable to me. I'm currently preparing for a trip - is it OK for you if a take a deeper look in the upcoming days? Will get back to you on Monday at the latest.

**Comment by feO2x** [comment]
Hey Chris,

I found some time early in the morning to take a closer look. I totally agree with everything you presented and I would add the following methods.

| Method name              | Safe? | Reason                                 |
|:-------------------------|:-----:|:---------------------------------------|
| `MustBeOfType` | ✅ | Only performs an explicit cast with the `as` operator which cannot cause enumeration |
| `IsSameAs` | ✅ | Calls `ReferenceEquals` which cannot result in enumeration |
| `MustNotBeSameAs` | ✅    | See `IsSameAs` |

I had a look at your branch, looks good to me. What's your opinion on these three additional methods? Would you be so kind and add the `NoEnumerationAttribute` to these methods, too, if you agree with me? Could you then please create a pull request that would merge with the `dev` branch? Thanks so much for your efforts in advance!

**Comment by feO2x** [comment]
The new version 10.1.0 is now released and contains your changes!
https://www.nuget.org/packages/Light.GuardClauses/10.1.0
